# Generated by Django 6.0.3 on 2026-03-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
